data<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
data1<-subset(data,Date=="1/2/2007"| Date =="2/2/2007")
png("plot1.png")
hist(as.numeric(as.character(data1$Global_active_power)),xlab="Global Active Power (kilowatts)",main="Global Active Power",col="red")
dev.off()