data<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
data1<-subset(data,Date=="1/2/2007"| Date =="2/2/2007")
png("plot4.png")
datetime<-numeric()
for (i in 1:nrow(data1)){
	datetime<-append(datetime,paste(c(as.character(data1$Date[i]),as.character(data1$Time[i])),collapse=":"))
}
datetime1<-strptime(datetime,'%d/%m/%Y:%H:%M:%S')
par(mfrow=c(2,2))
plot(datetime1,as.numeric(as.character(data1$Global_active_power)),type="n",ylab="Global Active Power",xlab="")
lines(datetime1,as.numeric(as.character(data1$Global_active_power)))
plot(datetime1,as.numeric(as.character(data1$Voltage)),type="n",ylab="Voltage")
lines(datetime1,as.numeric(as.character(data1$Voltage)))
plot(datetime1,as.numeric(as.character(data1$Sub_metering_1)),type="n",ylab="Energy sub metering")
lines(datetime1,as.numeric(as.character(data1$Sub_metering_1)))
lines(datetime1,as.numeric(as.character(data1$Sub_metering_2)),col="red")
lines(datetime1,as.numeric(as.character(data1$Sub_metering_3)),col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),lwd=c(2.5,2.5,2.5),col=c("black","red","blue"))
plot(datetime1,as.numeric(as.character(data1$Global_reactive_power)),type="n",ylab="Global reactive power")
lines(datetime1,as.numeric(as.character(data1$Global_reactive_power)))
dev.off()